export interface Book {
  id: number
  title: string
  author: string
  description: string
  price: number
  coverImage: string
  category: string
  ageGroup: string
  pages: number
  publishDate: string
  inStock: boolean
  isNew: boolean
  isBestseller: boolean
  featured: number // Higher number = more featured
}

export const bookData: Book[] = [
  {
    id: 1,
    title: "God's Love for Children",
    author: "Sarah Johnson",
    description:
      "A beautifully illustrated book that teaches young children about God's unconditional love through simple stories and colorful pictures.",
    price: 12.99,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "picture-books",
    ageGroup: "0-3",
    pages: 24,
    publishDate: "2023-10-15",
    inStock: true,
    isNew: true,
    isBestseller: false,
    featured: 8,
  },
  {
    id: 2,
    title: "The Brave Little Lion",
    author: "Michael Chen",
    description:
      "Follow the journey of a young lion who learns about courage, faith, and friendship as he faces challenges in the savanna.",
    price: 14.99,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "picture-books",
    ageGroup: "4-6",
    pages: 32,
    publishDate: "2023-08-22",
    inStock: true,
    isNew: false,
    isBestseller: true,
    featured: 9,
  },
  {
    id: 3,
    title: "Bible Heroes for Kids",
    author: "David Williams",
    description:
      "An engaging collection of Bible stories featuring heroes like David, Esther, and Daniel, written specifically for elementary school children.",
    price: 16.99,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "bible-stories",
    ageGroup: "7-9",
    pages: 48,
    publishDate: "2023-05-10",
    inStock: true,
    isNew: false,
    isBestseller: true,
    featured: 10,
  },
  {
    id: 4,
    title: "My First Prayer Book",
    author: "Emily Roberts",
    description:
      "A collection of simple prayers for young children to learn and recite, with colorful illustrations and easy-to-read text.",
    price: 9.99,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "picture-books",
    ageGroup: "0-3",
    pages: 20,
    publishDate: "2022-12-05",
    inStock: true,
    isNew: false,
    isBestseller: false,
    featured: 6,
  },
  {
    id: 5,
    title: "Adventures in Faith: The Journey Begins",
    author: "James Wilson",
    description:
      "The first book in a series following a group of friends who learn important lessons about faith, friendship, and making good choices.",
    price: 18.99,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "chapter-books",
    ageGroup: "10-12",
    pages: 120,
    publishDate: "2023-11-01",
    inStock: true,
    isNew: true,
    isBestseller: false,
    featured: 7,
  },
  {
    id: 6,
    title: "Christian Parenting: A Guide for Modern Families",
    author: "Dr. Rebecca Thompson",
    description:
      "A practical guide for parents on raising children with strong Christian values in today's challenging world.",
    price: 24.99,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "parenting",
    ageGroup: "parents",
    pages: 256,
    publishDate: "2023-02-15",
    inStock: true,
    isNew: false,
    isBestseller: true,
    featured: 8,
  },
  {
    id: 7,
    title: "Bible Activity Book",
    author: "Thomas Anderson",
    description:
      "A fun-filled activity book with puzzles, coloring pages, and games that help children learn Bible stories while having fun.",
    price: 11.99,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "activity-books",
    ageGroup: "4-6",
    pages: 64,
    publishDate: "2023-06-20",
    inStock: true,
    isNew: false,
    isBestseller: false,
    featured: 5,
  },
  {
    id: 8,
    title: "Math Made Fun: Christian Homeschool Edition",
    author: "Dr. Alan Peterson",
    description:
      "A mathematics workbook that integrates Christian themes and examples to make learning math engaging and relevant.",
    price: 19.99,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "educational",
    ageGroup: "7-9",
    pages: 96,
    publishDate: "2023-07-12",
    inStock: false,
    isNew: false,
    isBestseller: false,
    featured: 4,
  },
  {
    id: 9,
    title: "The Good Shepherd",
    author: "Maria Garcia",
    description: "A beautifully illustrated retelling of the parable of the Good Shepherd, perfect for young readers.",
    price: 13.99,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "bible-stories",
    ageGroup: "4-6",
    pages: 28,
    publishDate: "2023-09-05",
    inStock: true,
    isNew: true,
    isBestseller: false,
    featured: 7,
  },
  {
    id: 10,
    title: "Teen Devotional: 365 Days of Faith",
    author: "Pastor Kevin Johnson",
    description: "A year-long devotional specifically written for teenagers facing the challenges of modern life.",
    price: 22.99,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "educational",
    ageGroup: "13+",
    pages: 380,
    publishDate: "2023-01-01",
    inStock: true,
    isNew: false,
    isBestseller: true,
    featured: 9,
  },
  {
    id: 11,
    title: "Noah's Ark Counting Book",
    author: "Lisa Brown",
    description: "Learn to count with the animals on Noah's Ark in this educational picture book for young children.",
    price: 10.99,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "educational",
    ageGroup: "0-3",
    pages: 16,
    publishDate: "2023-04-18",
    inStock: true,
    isNew: false,
    isBestseller: false,
    featured: 6,
  },
  {
    id: 12,
    title: "Family Devotions for Busy Parents",
    author: "Pastor Robert Miller",
    description:
      "Short, meaningful devotions designed for busy families to connect with God together in just 10 minutes a day.",
    price: 17.99,
    coverImage: "/placeholder.svg?height=600&width=400",
    category: "parenting",
    ageGroup: "parents",
    pages: 208,
    publishDate: "2023-03-22",
    inStock: true,
    isNew: false,
    isBestseller: false,
    featured: 7,
  },
]
